# Generated by Django 6.0 on 2026-01-16 03:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cohort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cohort_name', models.CharField(max_length=255, verbose_name='اسم الدفعة')),
            ],
            options={
                'verbose_name': 'دفعة',
                'verbose_name_plural': 'الدفعات',
            },
        ),
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_name', models.CharField(max_length=255, verbose_name='اسم الكلية')),
            ],
            options={
                'verbose_name': 'كلية',
                'verbose_name_plural': 'الكليات',
            },
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_name', models.CharField(max_length=100, verbose_name='اسم المستوى')),
            ],
            options={
                'verbose_name': 'مستوى الدراسي',
                'verbose_name_plural': 'المستويات الدراسية',
            },
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester_name', models.CharField(max_length=255, verbose_name='اسم الفصل')),
            ],
            options={
                'verbose_name': 'الفصل دراسي',
                'verbose_name_plural': 'الفصول الدراسية',
            },
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization_name', models.CharField(max_length=255, verbose_name='اسم التخصص')),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='students.college', verbose_name='الكلية التابع لها')),
            ],
            options={
                'verbose_name': 'تخصص',
                'verbose_name_plural': 'التخصصات',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('academic_number', models.BigIntegerField(primary_key=True, serialize=False, unique=True, verbose_name='الرقم الأكاديمي')),
                ('student_name', models.CharField(max_length=255, verbose_name='اسم الطالب')),
                ('profile_picture', models.ImageField(upload_to='photos/%y/%m/%d', verbose_name='الصورة')),
                ('academic_status', models.CharField(choices=[('active', 'نشط'), ('suspended', 'موقف'), ('graduated', 'خريج')], max_length=10, verbose_name='الحالة الأكاديمية')),
                ('verification_method', models.CharField(choices=[('fingerprint', 'بصمة الإصبع'), ('barcode', 'باركود')], default='fingerprint', max_length=50, verbose_name='طريقة التحقق')),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='students.cohort', verbose_name='معرف الدفعة')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='students.level', verbose_name='المستوى الدراسي')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='students.semester', verbose_name='معرف الفصل')),
                ('specialization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='students.specialization', verbose_name='معرف التخصص')),
            ],
            options={
                'verbose_name': 'طالب',
                'verbose_name_plural': 'الطلاب',
            },
        ),
    ]
