# Generated by Django 6.0 on 2026-01-18 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='verification_method',
            field=models.CharField(choices=[('fingerprint', 'بصمة الإصبع'), ('barcode', 'باركود')], default='barcode', max_length=50, verbose_name='طريقة التحقق'),
        ),
    ]
