# Generated by Django 6.0 on 2026-01-23 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_student_verification_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='barcode_image',
            field=models.ImageField(blank=True, null=True, upload_to='barcodes/%y/%m/%d', verbose_name='صورة الباركود'),
        ),
    ]
