# Generated by Django 6.0 on 2026-01-30 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_student_barcode_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='verification_method',
        ),
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('male', 'ذكر'), ('female', 'أنثى')], default='male', max_length=10, verbose_name='الجنس'),
        ),
        migrations.AlterField(
            model_name='student',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='photos/%y/%m/%d', verbose_name='الصورة'),
        ),
    ]
