# Generated by Django 6.0 on 2026-03-25 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_alter_student_options_alter_student_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='cohort',
        ),
        migrations.DeleteModel(
            name='Cohort',
        ),
    ]
