# Generated by Django 6.0 on 2026-01-18 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SliderImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='slider_images/', verbose_name='الصورة')),
                ('caption', models.CharField(blank=True, max_length=255, null=True, verbose_name='وصف')),
                ('is_active', models.BooleanField(default=True, verbose_name='تفعيل')),
            ],
        ),
        migrations.CreateModel(
            name='UniversitySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='اسم الجامعة')),
                ('address', models.CharField(max_length=500, verbose_name='العنوان')),
                ('phone', models.CharField(max_length=50, verbose_name='رقم الهاتف')),
                ('whatsapp', models.CharField(max_length=50, verbose_name='رقم الواتساب')),
                ('email', models.EmailField(max_length=254, verbose_name='البريد الإلكتروني')),
                ('copyright_text', models.CharField(max_length=255, verbose_name='حقوق النشر')),
            ],
        ),
    ]
