# Generated by Django 6.0 on 2026-01-18 21:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UniversityBranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='اسم الفرع')),
                ('address', models.CharField(blank=True, max_length=500, verbose_name='العنوان')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='هاتف الفرع')),
            ],
            options={
                'verbose_name': 'فرع الجامعة',
                'verbose_name_plural': 'فروع الجامعة',
            },
        ),
        migrations.AlterModelOptions(
            name='sliderimage',
            options={'verbose_name': 'سلايدر', 'verbose_name_plural': 'صور السلايدرات'},
        ),
        migrations.AlterModelOptions(
            name='universitysettings',
            options={'verbose_name': 'الجامعة', 'verbose_name_plural': 'تفاصيل الجامعة'},
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='pages.universitybranch', verbose_name='الفرع التابع له')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'بروفايل الموظف',
                'verbose_name_plural': 'بروفايلات الموظفين',
            },
        ),
    ]
