# Generated by Django 6.0 on 2026-01-23 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_universitybranch_alter_sliderimage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='universitybranch',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='university/logos/', verbose_name='شعار الجامعة'),
        ),
    ]
