# Generated by Django 6.0 on 2026-01-23 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_universitybranch_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='universitybranch',
            name='logo',
        ),
    ]
