# Generated by Django 6.0 on 2026-01-23 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_remove_universitybranch_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='universitysettings',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='university/logos/', verbose_name='شعار الجامعة'),
        ),
    ]
