# Generated by Django 6.0 on 2026-01-16 03:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentFingerprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fingerprint_template', models.TextField(verbose_name='بيانات البصمة الرقمية')),
                ('finger_index', models.PositiveSmallIntegerField(default=1, verbose_name='رقم الإصبع')),
                ('fingerprint_quality', models.PositiveSmallIntegerField(help_text='درجة جودة البصمة من 1 إلى 100', verbose_name='جودة البصمة')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student', verbose_name='الطالب')),
            ],
            options={
                'verbose_name': 'بصمة طالب',
                'verbose_name_plural': 'بصمات الطلاب',
                'db_table': 'Student_Fingerprints',
            },
        ),
    ]
