# Generated by Django 6.0 on 2026-01-16 03:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(auto_now_add=True, verbose_name='تاريخ الإصدار')),
                ('end_date', models.DateField(verbose_name='تاريخ الانتهاء')),
                ('statement', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='حالة التصريح')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student', verbose_name='الطالب')),
            ],
            options={
                'verbose_name': 'تصريح',
                'verbose_name_plural': 'التصاريح',
                'db_table': 'Permits',
            },
        ),
    ]
