# Generated by Django 6.0 on 2026-01-16 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permit',
            name='statement',
            field=models.TextField(blank=True, null=True, verbose_name='البيان'),
        ),
    ]
