# Generated by Django 6.0 on 2026-01-16 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0002_alter_permit_statement'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='permit',
            table=None,
        ),
    ]
